version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-api-ts
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/clean-api-ts/dist
      - ./package.json:/usr/src/clean-api-ts/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo